// <auto-generated>
using System.Reflection;


namespace Microsoft.AspNetCore.Razor
{
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(SR)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }
#if !NET20
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
#endif
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
           var value = GetResourceString(resourceKey);
           if (formatterNames != null)
           {
               for (var i = 0; i < formatterNames.Length; i++)
               {
                   value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
               }
           }
           return value;
        }

        /// <summary>{0} ('{1}') must be a non-negative and non-zero value.</summary>
        internal static string @_0_1_must_be_a_non_negative_and_non_zero_value => GetResourceString("0_1_must_be_a_non_negative_and_non_zero_value");
        /// <summary>{0} ('{1}') must be a non-negative and non-zero value.</summary>
        internal static string Format0_1_must_be_a_non_negative_and_non_zero_value(object p0, object p1)
           => string.Format(Culture, GetResourceString("0_1_must_be_a_non_negative_and_non_zero_value"), p0, p1);

        /// <summary>{0} ('{1}') must be a non-negative value.</summary>
        internal static string @_0_1_must_be_a_non_negative_value => GetResourceString("0_1_must_be_a_non_negative_value");
        /// <summary>{0} ('{1}') must be a non-negative value.</summary>
        internal static string Format0_1_must_be_a_non_negative_value(object p0, object p1)
           => string.Format(Culture, GetResourceString("0_1_must_be_a_non_negative_value"), p0, p1);

        /// <summary>{0} ('{1}') must be a non-zero value.</summary>
        internal static string @_0_1_must_be_a_non_zero_value => GetResourceString("0_1_must_be_a_non_zero_value");
        /// <summary>{0} ('{1}') must be a non-zero value.</summary>
        internal static string Format0_1_must_be_a_non_zero_value(object p0, object p1)
           => string.Format(Culture, GetResourceString("0_1_must_be_a_non_zero_value"), p0, p1);

        /// <summary>{0} ('{1}') must be equal to '{2}'.</summary>
        internal static string @_0_1_must_be_equal_to_2 => GetResourceString("0_1_must_be_equal_to_2");
        /// <summary>{0} ('{1}') must be equal to '{2}'.</summary>
        internal static string Format0_1_must_be_equal_to_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_be_equal_to_2"), p0, p1, p2);

        /// <summary>{0} ('{1}') must be greater than '{2}'.</summary>
        internal static string @_0_1_must_be_greater_than_2 => GetResourceString("0_1_must_be_greater_than_2");
        /// <summary>{0} ('{1}') must be greater than '{2}'.</summary>
        internal static string Format0_1_must_be_greater_than_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_be_greater_than_2"), p0, p1, p2);

        /// <summary>{0} ('{1}') must be greater than or equal to '{2}'.</summary>
        internal static string @_0_1_must_be_greater_than_or_equal_to_2 => GetResourceString("0_1_must_be_greater_than_or_equal_to_2");
        /// <summary>{0} ('{1}') must be greater than or equal to '{2}'.</summary>
        internal static string Format0_1_must_be_greater_than_or_equal_to_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_be_greater_than_or_equal_to_2"), p0, p1, p2);

        /// <summary>{0} ('{1}') must be less than '{2}'.</summary>
        internal static string @_0_1_must_be_less_than_2 => GetResourceString("0_1_must_be_less_than_2");
        /// <summary>{0} ('{1}') must be less than '{2}'.</summary>
        internal static string Format0_1_must_be_less_than_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_be_less_than_2"), p0, p1, p2);

        /// <summary>{0} ('{1}') must be less than or equal to '{2}'.</summary>
        internal static string @_0_1_must_be_less_than_or_equal_to_2 => GetResourceString("0_1_must_be_less_than_or_equal_to_2");
        /// <summary>{0} ('{1}') must be less than or equal to '{2}'.</summary>
        internal static string Format0_1_must_be_less_than_or_equal_to_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_be_less_than_or_equal_to_2"), p0, p1, p2);

        /// <summary>{0} ('{1}') must not be equal to '{2}'.</summary>
        internal static string @_0_1_must_not_be_equal_to_2 => GetResourceString("0_1_must_not_be_equal_to_2");
        /// <summary>{0} ('{1}') must not be equal to '{2}'.</summary>
        internal static string Format0_1_must_not_be_equal_to_2(object p0, object p1, object p2)
           => string.Format(Culture, GetResourceString("0_1_must_not_be_equal_to_2"), p0, p1, p2);

        /// <summary>Cannot advance past the end of the buffer, which has a size of {0}.</summary>
        internal static string @Cannot_advance_past_end_of_the_buffer_which_has_a_size_of_0 => GetResourceString("Cannot_advance_past_end_of_the_buffer_which_has_a_size_of_0");
        /// <summary>Cannot advance past the end of the buffer, which has a size of {0}.</summary>
        internal static string FormatCannot_advance_past_end_of_the_buffer_which_has_a_size_of_0(object p0)
           => string.Format(Culture, GetResourceString("Cannot_advance_past_end_of_the_buffer_which_has_a_size_of_0"), p0);

        /// <summary>Cannot allocate a buffer of size {0}.</summary>
        internal static string @Cannot_allocate_a_buffer_of_size_0 => GetResourceString("Cannot_allocate_a_buffer_of_size_0");
        /// <summary>Cannot allocate a buffer of size {0}.</summary>
        internal static string FormatCannot_allocate_a_buffer_of_size_0(object p0)
           => string.Format(Culture, GetResourceString("Cannot_allocate_a_buffer_of_size_0"), p0);

        /// <summary>Destination is too short.</summary>
        internal static string @Destination_is_too_short => GetResourceString("Destination_is_too_short");
        /// <summary>Expected condition to be false.</summary>
        internal static string @Expected_condition_to_be_false => GetResourceString("Expected_condition_to_be_false");
        /// <summary>Expected '{0}' to be non-null.</summary>
        internal static string @Expected_0_to_be_non_null => GetResourceString("Expected_0_to_be_non_null");
        /// <summary>Expected '{0}' to be non-null.</summary>
        internal static string FormatExpected_0_to_be_non_null(object p0)
           => string.Format(Culture, GetResourceString("Expected_0_to_be_non_null"), p0);

        /// <summary>Expected condition to be true.</summary>
        internal static string @Expected_condition_to_be_true => GetResourceString("Expected_condition_to_be_true");
        /// <summary>File='{0}', Line={1}</summary>
        internal static string @File_0_Line_1 => GetResourceString("File_0_Line_1");
        /// <summary>File='{0}', Line={1}</summary>
        internal static string FormatFile_0_Line_1(object p0, object p1)
           => string.Format(Culture, GetResourceString("File_0_Line_1"), p0, p1);

        /// <summary>Non-negative number required.</summary>
        internal static string @Non_negative_number_required => GetResourceString("Non_negative_number_required");
        /// <summary>The value cannot be an empty string.</summary>
        internal static string @The_value_cannot_be_an_empty_string => GetResourceString("The_value_cannot_be_an_empty_string");
        /// <summary>The value cannot be an empty string or composed entirely of whitespace.</summary>
        internal static string @The_value_cannot_be_an_empty_string_composed_entirely_of_whitespace => GetResourceString("The_value_cannot_be_an_empty_string_composed_entirely_of_whitespace");
        /// <summary>This program location is thought to be unreachable.</summary>
        internal static string @This_program_location_is_thought_to_be_unreachable => GetResourceString("This_program_location_is_thought_to_be_unreachable");
        /// <summary>Unsupported type: '{0}'.</summary>
        internal static string @Unsupported_type_0 => GetResourceString("Unsupported_type_0");
        /// <summary>Unsupported type: '{0}'.</summary>
        internal static string FormatUnsupported_type_0(object p0)
           => string.Format(Culture, GetResourceString("Unsupported_type_0"), p0);

        /// <summary>Contains no elements</summary>
        internal static string @Contains_no_elements => GetResourceString("Contains_no_elements");
        /// <summary>Contains more than one element</summary>
        internal static string @Contains_more_than_one_element => GetResourceString("Contains_more_than_one_element");
        /// <summary>Contains no matching elements</summary>
        internal static string @Contains_no_matching_elements => GetResourceString("Contains_no_matching_elements");
        /// <summary>Contains more than one matching element</summary>
        internal static string @Contains_more_than_one_matching_element => GetResourceString("Contains_more_than_one_matching_element");

    }
}
