<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Anime.Desktop.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anime\Anime.csproj" />
    <ProjectReference Include="..\..\..\..\src\Miko.Windowing\Miko.Windowing.csproj" />
  </ItemGroup>

</Project>
