// The Chaldea licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using Miko.Windowing;
using Miko.Windowing.Video;
using Anime;

namespace Anime.Desktop;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        var context = App.CreateContext(builder => builder.UseSystemVideo());

        // Hot reload is wired up inside the shared app assembly, where the
        // handler is generated by Miko.Razor.Compiler.
        App.InitializeHotReload(context);

        context.RunDesktop();
    }
}
