using Miko.Routing;
using Miko.Windowing;

namespace MikoAppTransitions;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        var context = App.CreateContext();

        // Initialize the hot reload handler generated by Miko.Razor.Compiler.
        MikoHotReloadHandler.Initialize(context.GetHotReloadService());

        if (args.Contains("--auto-demo"))
            StartAutoDemo(context);

        context.RunDesktop();
    }

    /// <summary>
    /// 自动演示模式（--auto-demo）：每 2.5s 循环执行 前进(modal) → 返回 → 前进(fade) → 返回，
    /// 配合 Trace 级日志在控制台观察转场每一帧的推进（dt / elapsed / progress）。
    /// </summary>
    private static void StartAutoDemo(Miko.Hosting.MikoAppContext context)
    {
        var nav = (NavigationManager)context.Services.GetService(typeof(NavigationManager))!;
        var steps = new Action[]
        {
            () => nav.NavigateTo("/detail/modal", NavigationDirection.Forward, PageTransitions.Create("modal", reverse: false)),
            () => nav.NavigateTo("/", NavigationDirection.Back, PageTransitions.Create("modal", reverse: true)),
            () => nav.NavigateTo("/detail/fade", NavigationDirection.Forward, PageTransitions.Create("fade", reverse: false)),
            () => nav.NavigateTo("/", NavigationDirection.Back, PageTransitions.Create("fade", reverse: true)),
        };

        var i = 0;
        var timer = new System.Timers.Timer(2500) { AutoReset = true };
        timer.Elapsed += (_, _) =>
        {
            Console.WriteLine($"[auto-demo] step {i}: {steps[i % steps.Length].Method.Name}");
            steps[i % steps.Length]();
            i++;
        };
        timer.Start();
    }
}
