---
to: <%= context.path %>
force: true
---
/*
 * This code is generated by 'node generator.js' command, do not modify this file manually.
 */<%for(let src of context.imports){%>
@import "<%= src %>";<%}%>