using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Miko.SourceGenerators.Models;

namespace Miko.SourceGenerators;

[Generator]
public class StylePropertyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 查找 Style 类
        var styleProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsStyleClass(node),
                transform: static (ctx, _) => GetStyleInfo(ctx))
            .Where(static info => info != null);

        context.RegisterSourceOutput(styleProvider, static (spc, styleInfo) => Execute(spc, styleInfo!));
    }

    private static bool IsStyleClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cls &&
               cls.Identifier.Text == "Style";
    }

    private static StyleInfo? GetStyleInfo(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (classSymbol == null)
            return null;

        // 检查是否是 Miko.Styling.Style
        if (classSymbol.ContainingNamespace?.ToDisplayString() != "Miko.Styling")
            return null;

        var properties = new List<PropertyInfo>();

        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IPropertySymbol property)
                continue;

            // 跳过简写属性（Padding, Margin, Border 等）
            if (IsShorthandProperty(property.Name))
                continue;

            var propertyType = property.Type;
            var isNullable = propertyType.NullableAnnotation == NullableAnnotation.Annotated;

            // 只处理可空属性和集合属性
            if (!isNullable && !IsCollectionType(propertyType))
                continue;

            properties.Add(new PropertyInfo
            {
                Name = property.Name,
                Type = propertyType.ToDisplayString(),
                IsNullable = isNullable,
                IsValueType = propertyType.IsValueType
            });
        }

        return new StyleInfo { Properties = properties };
    }

    private static bool IsShorthandProperty(string name)
    {
        return name is "Padding" or "Margin" or "Border" or "BorderTop" or "BorderRight"
            or "BorderBottom" or "BorderLeft" or "BorderRadius" or "Overflow" or "Flex";
    }

    private static bool IsCollectionType(ITypeSymbol type)
    {
        var typeName = type.ToDisplayString();
        return typeName.StartsWith("System.Collections.Generic.List<");
    }

    private static void Execute(SourceProductionContext context, StyleInfo styleInfo)
    {
        // 生成 HasAnyProperty 方法
        var hasAnyPropertySource = GenerateHasAnyProperty(styleInfo);
        context.AddSource("Style.HasAnyProperty.g.cs", SourceText.From(hasAnyPropertySource, Encoding.UTF8));

        // 生成 Merge 辅助方法
        var mergeSource = GenerateMergeHelper(styleInfo);
        context.AddSource("Style.MergeHelper.g.cs", SourceText.From(mergeSource, Encoding.UTF8));

        // 生成 ComputedStyle.FromStyle 辅助方法
        var fromStyleSource = GenerateFromStyleHelper(styleInfo);
        context.AddSource("ComputedStyle.FromStyleHelper.g.cs", SourceText.From(fromStyleSource, Encoding.UTF8));
    }

    private static string GenerateHasAnyProperty(StyleInfo styleInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Miko.Styling;");
        sb.AppendLine();
        sb.AppendLine("public partial class Style");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 判断样式对象是否有任何非空属性（自动生成）");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasAnyProperty()");
        sb.AppendLine("    {");
        sb.Append("        return ");

        var conditions = styleInfo.Properties
            .Select(p => $"{p.Name} != null")
            .ToList();

        for (int i = 0; i < conditions.Count; i++)
        {
            if (i > 0)
                sb.Append(" ||\n               ");
            sb.Append(conditions[i]);
        }

        sb.AppendLine(";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateMergeHelper(StyleInfo styleInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Miko.Styling;");
        sb.AppendLine();
        sb.AppendLine("public partial class Style");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 合并样式的自动生成部分");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    partial void MergeGenerated(Style other)");
        sb.AppendLine("    {");

        foreach (var prop in styleInfo.Properties)
        {
            sb.AppendLine($"        {prop.Name} ??= other.{prop.Name};");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateFromStyleHelper(StyleInfo styleInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Miko.Styling;");
        sb.AppendLine();
        sb.AppendLine("public partial class ComputedStyle");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 应用样式属性的自动生成部分");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    partial void ApplyStylePropertiesGenerated(Style style)");
        sb.AppendLine("    {");

        foreach (var prop in styleInfo.Properties)
        {
            if (prop.IsNullable && prop.IsValueType)
            {
                // 可空值类型：if (style.Display.HasValue) Display = style.Display.Value;
                sb.AppendLine($"        if (style.{prop.Name}.HasValue) {prop.Name} = style.{prop.Name}.Value;");
            }
            else
            {
                // 引用类型：if (style.FontFamily != null) FontFamily = style.FontFamily;
                sb.AppendLine($"        if (style.{prop.Name} != null) {prop.Name} = style.{prop.Name};");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
