using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Microsoft.CodeAnalysis.Razor.Compiler.SourceGenerators;

/// <summary>
/// Source generator that creates a hot reload metadata update handler when hot reload is enabled.
/// This allows applications to rebuild their UI without closing the window when code changes.
/// </summary>
[Generator]
public class HotReloadHandlerGenerator : IIncrementalGenerator
{
    private const string MikoAppBuilderType = "Miko.Hosting.MikoAppBuilder";
    private const string EnableHotReloadMethod = "EnableHotReload";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register a syntax receiver to detect EnableHotReload() calls
        var enableHotReloadInvocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsEnableHotReloadInvocation(node),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Combine with compilation to get namespace and assembly info
        var compilationAndInvocations = context.CompilationProvider.Combine(enableHotReloadInvocations.Collect());

        // Generate the hot reload handler if any EnableHotReload calls are found
        context.RegisterSourceOutput(compilationAndInvocations,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsEnableHotReloadInvocation(SyntaxNode node)
    {
        // Look for invocation expressions like builder.EnableHotReload()
        if (node is not InvocationExpressionSyntax invocation)
            return false;

        // Check if the method name is EnableHotReload
        var expression = invocation.Expression;
        if (expression is MemberAccessExpressionSyntax memberAccess)
        {
            return memberAccess.Name.Identifier.Text == EnableHotReloadMethod;
        }

        return false;
    }

    private static string? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        var symbolInfo = context.SemanticModel.GetSymbolInfo(invocation);

        if (symbolInfo.Symbol is not IMethodSymbol methodSymbol)
            return null;

        // Verify this is actually MikoAppBuilder.EnableHotReload()
        if (methodSymbol.ContainingType?.ToDisplayString() != MikoAppBuilderType)
            return null;

        if (methodSymbol.Name != EnableHotReloadMethod)
            return null;

        return methodSymbol.Name; // Return a marker indicating we found it
    }

    private static void Execute(Compilation compilation, ImmutableArray<string?> invocations, SourceProductionContext context)
    {
        // If no EnableHotReload() calls found, don't generate anything
        if (invocations.IsEmpty || invocations.All(i => i is null))
            return;

        // Get the root namespace from the assembly
        var assemblyName = compilation.AssemblyName ?? "Application";
        var rootNamespace = GetRootNamespace(compilation) ?? assemblyName.Replace(".", "_");

        // Generate the hot reload handler
        var source = GenerateHotReloadHandler(rootNamespace);

        // Add the generated source to the compilation
        context.AddSource("MikoHotReloadHandler.g.cs", source);
    }

    private static string? GetRootNamespace(Compilation compilation)
    {
        // Use the assembly name as the root namespace
        // For MikoApp1.Razor, this will be "MikoApp1.Razor"
        var assemblyName = compilation.AssemblyName;
        if (!string.IsNullOrEmpty(assemblyName))
            return assemblyName;

        // Fallback: try to find the most common namespace in the compilation
        var namespaces = compilation.SyntaxTrees
            .SelectMany(tree => tree.GetRoot().DescendantNodes())
            .OfType<NamespaceDeclarationSyntax>()
            .Select(ns => ns.Name.ToString())
            .GroupBy(ns => ns)
            .OrderByDescending(g => g.Count())
            .Select(g => g.Key)
            .FirstOrDefault();

        return namespaces;
    }

    private static string GenerateHotReloadHandler(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Reflection.Metadata;");
        sb.AppendLine("using Miko.Hosting;");
        sb.AppendLine();
        sb.AppendLine($"[assembly: MetadataUpdateHandler(typeof({rootNamespace}.MikoHotReloadHandler))]");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated hot reload handler for this Miko application.");
        sb.AppendLine("    /// Generated because EnableHotReload() was called in the application builder.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class MikoHotReloadHandler");
        sb.AppendLine("    {");
        sb.AppendLine("        private static HotReloadService? _service;");
        sb.AppendLine();
        sb.AppendLine("        internal static void Initialize(HotReloadService service)");
        sb.AppendLine("        {");
        sb.AppendLine("            _service = service;");
        sb.AppendLine("            Console.WriteLine(\"[HotReload] Auto-generated handler initialized.\");");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Called by the .NET runtime when hot reload occurs.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void UpdateApplication(Type[]? updatedTypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            var count = updatedTypes?.Length ?? 0;");
        sb.AppendLine("            Console.WriteLine($\"[HotReload] UpdateApplication called, {count} types updated.\");");
        sb.AppendLine("            _service?.TriggerReload();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Called by the .NET runtime before metadata is applied.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static void ClearCache(Type[]? updatedTypes)");
        sb.AppendLine("        {");
        sb.AppendLine("            // Optional: Clear any application-specific caches here");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
