<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationId>com.miko.playerdemo</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Miko.Components/Miko.Components.csproj" />
    <ProjectReference Include="../../../src/Miko.Android/Miko.Android.csproj" />
    <AndroidAsset Include="../../Media/MikoApp.Media/Assets/miko-local.mp4" Link="miko-local.mp4" />
  </ItemGroup>
</Project>
