using Miko.Windowing;
using MikoMultiplatformApp;

namespace MikoMultiplatformApp.Desktop;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        var context = App.CreateContext();

        // Hot reload is wired up inside the shared app assembly, where the
        // handler is generated by Miko.Razor.Compiler.
        App.InitializeHotReload(context);

        context.RunDesktop();
    }
}
