---
to: <%= context.path %>
force: true
---
/*
 * This code is generated by 'node generator.js' command, do not modify this file manually.
 */
namespace Miko
{
    internal static class IconResource
    {
        private static readonly Dictionary<string, string> Store = new()
        {<%for(let icon of context.icons){%>
            {"<%- icon.name %>", @"<%- icon.content %>"},<%}%>
        };

        public static IDictionary<string, string> Icons => Store;

        public static string Get(string name)
        {
            return Store[name];
        }
    }
}
