namespace MikoRazorApp;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        var app = App.Create();

        // Initialize the hot reload handler generated by Miko.Razor.Compiler.
        MikoHotReloadHandler.Initialize(app.GetHotReloadService());

        app.Run();
    }
}
