using Miko.Windowing;

namespace MikoAppSidemenu;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        var context = App.CreateContext();

        // Initialize the hot reload handler generated by Miko.Razor.Compiler.
        MikoHotReloadHandler.Initialize(context.GetHotReloadService());

        context.RunDesktop();
    }
}
