using Miko.Common;
using Miko.Styling;

namespace Miko.Ionic.Components;

/// <summary>
/// Styles for the list components (<c>ion-list</c>, <c>ion-list-header</c>).
/// Ported from the Ionic source: <c>list.scss</c> / <c>list.md.scss</c> / <c>list.ios.scss</c>,
/// <c>list-header.scss</c>. Item-owned rules are generated by <see cref="BaseItemStyles"/>.
/// <para>
/// Rules are scoped by the active mode class (<c>md</c> / <c>ios</c>); see
/// <see cref="PageStyles"/> for the mode-scoping rationale.
/// </para>
/// </summary>
internal static class ListStyles
{
    internal static CssObject GenStyle(string mode, IonicTheme t)
    {
        var css = new CssObject
        {
            // ion-list — vertical stack of items with a small top/bottom inset.
            [$".ion-list.{mode}"] = new()
            {
                Display = Display.Block,
                Width = Length.Percent(100),
                BackgroundColor = t.ListBackground,
                PaddingTop = Length.Px(8),
                PaddingBottom = Length.Px(8),
            },

            // list-inset (list.md.scss / list.ios.scss .list-{mode}.list-inset): margin around
            // the list, rounded corners, clipped content (list.scss: overflow hidden).
            [$".ion-list.{mode}.list-inset"] = new()
            {
                MarginTop = Length.Px(t.ListInsetMargin),
                MarginBottom = Length.Px(t.ListInsetMargin),
                MarginLeft = Length.Px(t.ListInsetMargin),
                MarginRight = Length.Px(t.ListInsetMargin),
                BorderRadius = new BorderRadius(Length.Px(t.ListInsetBorderRadius)),
                OverflowX = Overflow.Hidden,
                OverflowY = Overflow.Hidden,
            },

            // Two adjacent inset lists collapse the gap between them
            // (list.md.scss / list.ios.scss: .list-{mode}.list-inset + ion-list.list-inset).
            [$".ion-list.{mode}.list-inset + .ion-list.list-inset"] = new()
            {
                MarginTop = Length.Px(0),
            },

            // ion-list-header — section header above the items.
            [$".ion-list-header.{mode}"] = new()
            {
                Display = Display.Flex,
                AlignItems = AlignItems.Center,
                JustifyContent = JustifyContent.SpaceBetween,
                Width = Length.Percent(100),
                MinHeight = Length.Px(t.ItemMinHeight),
                PaddingLeft = Length.Px(t.ItemPaddingStart),
                PaddingRight = Length.Px(t.ItemPaddingStart),
                BackgroundColor = Color.Transparent,
                FontSize = Length.Px(t.ListHeaderFontSize),
                FontWeight = FontWeight.Medium,
                Color = t.ListHeaderColor,
                Overflow = Overflow.Hidden,
            },

            // list-header.scss .list-header-inner — the inner row carries inset lines and keeps
            // the default slot laid out as a single flex row.
            [$".ion-list-header.{mode} .list-header-inner"] = new()
            {
                Display = Display.Flex,
                Position = Position.Relative,
                Flex = 1,
                AlignItems = AlignItems.Center,
                AlignSelf = AlignSelf.Stretch,
                MinHeight = Inherit,
                Overflow = Overflow.Hidden,
            },

            // list-header.scss ::slotted(ion-label) { flex: 1 1 auto; }. Only a label in the
            // header's own default slot receives this, not labels nested inside child controls.
            [$".ion-list-header.{mode} .list-header-inner > .ion-label"] = new()
            {
                Flex = Flex.Auto,
            },

            // `lines="full"` draws across the host; `lines="inset"` starts after the host's
            // leading padding by drawing on the inner row; `none` keeps both surfaces borderless.
            [$".ion-list-header.{mode}.list-header-lines-full"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(1), BorderStyle.Solid, t.ItemBorderColor),
            },
            [$".ion-list-header.{mode}.list-header-lines-full .list-header-inner"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(0), BorderStyle.None, Color.Transparent),
            },
            [$".ion-list-header.{mode}.list-header-lines-inset"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(0), BorderStyle.None, Color.Transparent),
            },
            [$".ion-list-header.{mode}.list-header-lines-inset .list-header-inner"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(1), BorderStyle.Solid, t.ItemBorderColor),
            },
            [$".ion-list-header.{mode}.list-header-lines-none"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(0), BorderStyle.None, Color.Transparent),
            },
            [$".ion-list-header.{mode}.list-header-lines-none .list-header-inner"] = new()
            {
                BorderBottom = new BorderSide(Length.Px(0), BorderStyle.None, Color.Transparent),
            },

        };

        AddListHeaderColor(css, mode, "primary", t.Primary, Color.White);
        AddListHeaderColor(css, mode, "secondary", t.Secondary, Color.White);
        AddListHeaderColor(css, mode, "tertiary", t.Tertiary, Color.White);
        AddListHeaderColor(css, mode, "success", t.Success, Color.Black);
        AddListHeaderColor(css, mode, "warning", t.Warning, Color.Black);
        AddListHeaderColor(css, mode, "danger", t.Danger, Color.White);
        AddListHeaderColor(css, mode, "light", t.Light, Color.Black);
        AddListHeaderColor(css, mode, "medium", t.Medium, Color.White);
        AddListHeaderColor(css, mode, "dark", t.Dark, Color.White);

        return css;
    }

    private static void AddListHeaderColor(
        CssObject css, string mode, string name, Color background, Color color)
    {
        css[$".ion-list-header.{mode}.ion-color-{name}"] = new()
        {
            BackgroundColor = background,
            Color = color,
        };
    }

}
