using Miko.Windowing;
using Miko.Windowing.Native;
using MikoAppBlank;

namespace MikoAppBlank.Desktop;

public static class Program
{
    [STAThread]
    public static void Main(string[] args)
    {
        // UseDesktopNative() supplies the desktop implementations of the Miko.Native
        // capability interfaces (filesystem, clipboard, device, network, …). Capabilities
        // with no desktop system stack keep throwing PlatformNotSupportedException.
        var context = App.CreateContext(builder => builder.UseDesktopNative());

        // Hot reload is wired up inside the shared app assembly, where the
        // handler is generated by Miko.Razor.Compiler.
        App.InitializeHotReload(context);

        context.RunDesktop();
    }
}
